version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /packages/smartthings-gateway
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /packages/smartthings-gateway
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /deploy/smartthings-gateway
    schedule:
      interval: weekly
